ALTER TABLE users ADD COLUMN deleted_at INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN deleted_by INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN deleted_at INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN deleted_by INTEGER DEFAULT 0;
ALTER TABLE comments ADD COLUMN deleted_at INTEGER DEFAULT 0;
ALTER TABLE comments ADD COLUMN deleted_by INTEGER DEFAULT 0;
ALTER TABLE plugins ADD COLUMN deleted_at INTEGER DEFAULT 0;
ALTER TABLE plugins ADD COLUMN deleted_by INTEGER DEFAULT 0;
